language: node_js

sudo: false

node_js:
- '8'

branches:
  only:
  - master

cache:
  directories:
  - node_modules
  - ~/.npm

# S: Build Lifecycle
before_install:
- git config --global user.name 'wkbp'
- git config --global user.email 519591497@qq.com

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm i hexo-renderer-marked --save

script:
- hexo clean
- hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Travis"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

env:
 global:
   - GH_REF: github.com/wkbp/wkbp.github.io.git

